typography_spectrum: 0.11414732853882015
color:
  brandStrength: 0.9569670942146331
  lightness: 0.9292566971853375
  saturation: 0.5505252676084638
  rhythmicContrast: 0.16461480874568224
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
opengraph:
  type: Business Page
  appId: '@MonicaGriesYourTrueLendingPartner'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/399a613b-eeaa-4997-99ce-8300bb6fc1ed.jpg
layout_spectrum: 0.3254039303865284
author:
  name: Monica Gries
  email: mgries@myamcap.com
  url: 'http://www.amcapgulfcoast.com/EmployeeDetail.aspx?EmployeeID=77284&'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68d93d46-66d1-49b8-a8d3-1471e5ea39af.jpg
name: Monica Gries Your True Lending Partner
title: A Mortgage Company You Can Trust & Count On
description: AmCap Mortgage LTD. - Gulf Coast Division
